image:
  repository: gcr.io/bricklens/render
  tag: latest
  pullPolicy: Always  # Force image pull

imagePullSecrets:
  - name: gcr-image-pull-token

parallelism: 10

resources:
  requests:
    cpu: "500m"
    memory: "8Gi"
  limits:
    cpu: "8000m"
    memory: "64Gi"
