image:
  repository: gcr.io/bricklens/render
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: gcr-image-pull-token

parallelism: 2

resources:
  requests:
    cpu: "4"
    memory: "8Gi"
  limits:
    cpu: "4"
    memory: "32Gi"
