install:
  poetry install

build: install
  poetry build

build-docker:
  docker build -t gcr.io/bricklens/render -f docker/Dockerfile.render .

push-docker: build-docker
  docker push -t gcr.io/bricklens/render

