install:
  poetry install

build: install
  poetry build

build-docker: build
  docker build -t gcr.io/bricklens/render:latest -f deploy/docker/Dockerfile.render .

push-docker:
  docker push gcr.io/bricklens/render:latest

