install-deps:

install:
  # The following is needed due to issues with the latest setuptools.
  # See: https://github.com/python-poetry/poetry/issues/1584
  # Poetry 1.20.0 should fix this problem.
  poetry run pip install -U setuptools==57
  poetry install

build: install
  poetry build

build-docker: build
  docker build -t gcr.io/bricklens/render:latest -f deploy/docker/Dockerfile.render .

push-docker: build-docker
  docker push gcr.io/bricklens/render:latest

