apiVersion: batch/v1
kind: Job
metadata:
  name: bricklens-render
spec:
  parallelism: {{ .Values.parallelism }}
  completions: {{ .Values.parallelism }}
  backoffLimit: 4
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      restartPolicy: Never
      terminationGracePeriodSeconds: 120
      containers:
        - name: bricklens-render
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          command: ["./render.sh"]
          args:
            - ./render.sh
          env:
          - name: BRICKLENS_TIMESTAMP
            value: {{ now | date "2006-01-02T15:04:05" }}
          - name: BRICKLENS_JOB_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
